### PR TITLE
containers/common 0.56.0, skopeo 1.13.3, buildah 1.32.0

### PR DESCRIPTION
**Pull request by AndreasAlbertQC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by AndreasAlbertQC** [comment]
@conda-forge/containers-common-feedstock, this is ready for review

**Comment by xhochy** [comment]
> @conda-forge/containers-common-feedstock, this is ready for review

 @conda-forge/containers-common, this is ready for review
 
 Teams are without the `-feedstock` ;)

**Comment by AndreasAlbertQC** [comment]
@xhochy thanks for the hint, doesn't show up for me either, though. Do I have to be a part of the conda-forge orga to be able to resolve the link to the team?

**Comment by xhochy** [comment]
Yes. That could be the issue. This is resolved once this PR is merged.

**Review by pavelzw — COMMENTED** [review]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=799902&view=artifacts&pathAsName=false&type=publishedArtifacts something with the build is still off. 
image
image

**Comment by AndreasAlbertQC** [comment]
thanks for checking @pavelzw should be fixed now. I went with the previous behavior that we want these lines to be uncommented.

**Comment by AndreasAlbertQC** [comment]
containers.conf looks OK to me now. For reference, here are the four places the sed command touches, as present in the latest build artiface:

```conf
# Path to the seccomp.json profile which is used as the default seccomp profile
# for the runtime.
#
seccomp_profile = "/home/conda/feedstock_root/build_artifacts/containers-common_1696846379147/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/containers/seccomp.json"
```


```conf
# Path to directory where CNI plugin binaries are located.
#
cni_plugin_dirs = [
"/usr/local/libexec/cni",
"/home/conda/feedstock_root/build_artifacts/containers-common_1696846379147/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cni",
"/usr/local/lib/cni",
"/usr/lib/cni",
"/opt/cni/bin",
]
```


```conf
# Path to the directory where network configuration files are located.
# For the CNI backend the default is "/etc/cni/net.d" as root
# and "$HOME/.config/cni/net.d" as rootless.
# For the netavark backend "/etc/containers/networks" is used as root
# and "$graphroot/networks" as rootless.
#
network_config_dir = "/home/conda/feedstock_root/build_artifacts/containers-common_1696846379147/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/etc/cni/net.d/"

```

```
# Path to OCI hooks directories for automatically executed hooks.
#
hooks_dir = [
"/home/conda/feedstock_root/build_artifacts/containers-common_1696846379147/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/containers/oci/hooks.d",
]
```

**Review by xhochy — APPROVED** [review]

**Pull request merged**
